// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: vpsimage.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Image {

  /// <summary>Holder for reflection information generated from vpsimage.proto</summary>
  public static partial class VpsimageReflection {

    #region Descriptor
    /// <summary>File descriptor for vpsimage.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static VpsimageReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg52cHNpbWFnZS5wcm90bxIFaW1hZ2UigAEKDEltYWdlUmVxdWVzdBIPCgdt",
            "ZXNzYWdlGAEgASgJEhIKCmJ5dGVzSW1hZ2UYAiABKAwSJAoLZ3BzUG9zaXRp",
            "b24YAyABKAsyDy5pbWFnZS5Qb3NpdGlvbhIlCgpjYW1lcmFJbmZvGAQgASgL",
            "MhEuaW1hZ2UuQ2FtZXJhSW5mbyKKAQoNSW1hZ2VSZXNwb25zZRIPCgdtZXNz",
            "YWdlGAEgASgJEhAKCGFjY3VyYWN5GAIgASgCEikKCXdvcmxkQ29vchgDIAEo",
            "CzIWLmltYWdlLldvcmxkQ29vcmRpbmF0ZRIrCgpjb2xtYXBDb29yGAQgASgL",
            "MhcuaW1hZ2UuQ29sbWFwQ29vcmRpbmF0ZSJmChRBdmFpbGFibGVBcmVhUmVx",
            "dWVzdBIkCgtncHNQb3NpdGlvbhgBIAEoCzIPLmltYWdlLlBvc2l0aW9uEhMK",
            "C21heERpc3RhbmNlGAIgASgFEhMKC21pbkRpc3RhbmNlGAMgASgFImMKFUF2",
            "YWlsYWJsZUFyZWFSZXNwb25zZRIPCgdtZXNzYWdlGAEgASgJEhMKC2lzQXZh",
            "aWxhYmxlGAIgASgIEiQKC2dwc1Bvc2l0aW9uGAMgASgLMg8uaW1hZ2UuUG9z",
            "aXRpb24iQQoIUG9zaXRpb24SEAoIbGF0aXR1ZGUYASABKAESEQoJbG9uZ2l0",
            "dWRlGAIgASgBEhAKCGFsdGl0dWRlGAMgASgBImYKD1dvcmxkQ29vcmRpbmF0",
            "ZRIQCghsYXRpdHVkZRgBIAEoARIRCglsb25naXR1ZGUYAiABKAESEAoIYWx0",
            "aXR1ZGUYAyABKAESDQoFdXRtX3gYBCABKAESDQoFdXRtX3kYBSABKAEiigEK",
            "EENvbG1hcENvb3JkaW5hdGUSCgoCcXcYASABKAESCgoCcXgYAiABKAESCgoC",
            "cXkYAyABKAESCgoCcXoYBCABKAESCgoCdHgYBSABKAESCgoCdHkYBiABKAES",
            "CgoCdHoYByABKAESCgoCcHgYCCABKAESCgoCcHkYCSABKAESCgoCcHoYCiAB",
            "KAEicgoKQ2FtZXJhSW5mbxIYChBwaXhlbEZvY2FsTGVuZ3RoGAEgASgCEhcK",
            "D3ByaW5jaXBhbFBvaW50WBgCIAEoAhIXCg9wcmluY2lwYWxQb2ludFkYAyAB",
            "KAISGAoQcmFkaWFsRGlzdG9ydGlvbhgEIAEoAjJBCgVJbWFnZRI4CglTZW5k",
            "SW1hZ2USEy5pbWFnZS5JbWFnZVJlcXVlc3QaFC5pbWFnZS5JbWFnZVJlc3Bv",
            "bnNlIgAyUQoLSW1hZ2VTdHJlYW0SQgoPU2VuZFN0cmVhbUltYWdlEhMuaW1h",
            "Z2UuSW1hZ2VSZXF1ZXN0GhQuaW1hZ2UuSW1hZ2VSZXNwb25zZSIAKAEwATJi",
            "Cg1BdmFpbGFibGVBcmVhElEKEkNoZWNrQXZhaWxhYmxlQXJlYRIbLmltYWdl",
            "LkF2YWlsYWJsZUFyZWFSZXF1ZXN0GhwuaW1hZ2UuQXZhaWxhYmxlQXJlYVJl",
            "c3BvbnNlIgBiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Image.ImageRequest), global::Image.ImageRequest.Parser, new[]{ "Message", "BytesImage", "GpsPosition", "CameraInfo" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Image.ImageResponse), global::Image.ImageResponse.Parser, new[]{ "Message", "Accuracy", "WorldCoor", "ColmapCoor" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Image.AvailableAreaRequest), global::Image.AvailableAreaRequest.Parser, new[]{ "GpsPosition", "MaxDistance", "MinDistance" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Image.AvailableAreaResponse), global::Image.AvailableAreaResponse.Parser, new[]{ "Message", "IsAvailable", "GpsPosition" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Image.Position), global::Image.Position.Parser, new[]{ "Latitude", "Longitude", "Altitude" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Image.WorldCoordinate), global::Image.WorldCoordinate.Parser, new[]{ "Latitude", "Longitude", "Altitude", "UtmX", "UtmY" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Image.ColmapCoordinate), global::Image.ColmapCoordinate.Parser, new[]{ "Qw", "Qx", "Qy", "Qz", "Tx", "Ty", "Tz", "Px", "Py", "Pz" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Image.CameraInfo), global::Image.CameraInfo.Parser, new[]{ "PixelFocalLength", "PrincipalPointX", "PrincipalPointY", "RadialDistortion" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class ImageRequest : pb::IMessage<ImageRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ImageRequest> _parser = new pb::MessageParser<ImageRequest>(() => new ImageRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ImageRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Image.VpsimageReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ImageRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ImageRequest(ImageRequest other) : this() {
      message_ = other.message_;
      bytesImage_ = other.bytesImage_;
      gpsPosition_ = other.gpsPosition_ != null ? other.gpsPosition_.Clone() : null;
      cameraInfo_ = other.cameraInfo_ != null ? other.cameraInfo_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ImageRequest Clone() {
      return new ImageRequest(this);
    }

    /// <summary>Field number for the "message" field.</summary>
    public const int MessageFieldNumber = 1;
    private string message_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Message {
      get { return message_; }
      set {
        message_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "bytesImage" field.</summary>
    public const int BytesImageFieldNumber = 2;
    private pb::ByteString bytesImage_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString BytesImage {
      get { return bytesImage_; }
      set {
        bytesImage_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "gpsPosition" field.</summary>
    public const int GpsPositionFieldNumber = 3;
    private global::Image.Position gpsPosition_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Image.Position GpsPosition {
      get { return gpsPosition_; }
      set {
        gpsPosition_ = value;
      }
    }

    /// <summary>Field number for the "cameraInfo" field.</summary>
    public const int CameraInfoFieldNumber = 4;
    private global::Image.CameraInfo cameraInfo_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Image.CameraInfo CameraInfo {
      get { return cameraInfo_; }
      set {
        cameraInfo_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ImageRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ImageRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Message != other.Message) return false;
      if (BytesImage != other.BytesImage) return false;
      if (!object.Equals(GpsPosition, other.GpsPosition)) return false;
      if (!object.Equals(CameraInfo, other.CameraInfo)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Message.Length != 0) hash ^= Message.GetHashCode();
      if (BytesImage.Length != 0) hash ^= BytesImage.GetHashCode();
      if (gpsPosition_ != null) hash ^= GpsPosition.GetHashCode();
      if (cameraInfo_ != null) hash ^= CameraInfo.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Message.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Message);
      }
      if (BytesImage.Length != 0) {
        output.WriteRawTag(18);
        output.WriteBytes(BytesImage);
      }
      if (gpsPosition_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(GpsPosition);
      }
      if (cameraInfo_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(CameraInfo);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Message.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Message);
      }
      if (BytesImage.Length != 0) {
        output.WriteRawTag(18);
        output.WriteBytes(BytesImage);
      }
      if (gpsPosition_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(GpsPosition);
      }
      if (cameraInfo_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(CameraInfo);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Message.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Message);
      }
      if (BytesImage.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(BytesImage);
      }
      if (gpsPosition_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(GpsPosition);
      }
      if (cameraInfo_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(CameraInfo);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ImageRequest other) {
      if (other == null) {
        return;
      }
      if (other.Message.Length != 0) {
        Message = other.Message;
      }
      if (other.BytesImage.Length != 0) {
        BytesImage = other.BytesImage;
      }
      if (other.gpsPosition_ != null) {
        if (gpsPosition_ == null) {
          GpsPosition = new global::Image.Position();
        }
        GpsPosition.MergeFrom(other.GpsPosition);
      }
      if (other.cameraInfo_ != null) {
        if (cameraInfo_ == null) {
          CameraInfo = new global::Image.CameraInfo();
        }
        CameraInfo.MergeFrom(other.CameraInfo);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Message = input.ReadString();
            break;
          }
          case 18: {
            BytesImage = input.ReadBytes();
            break;
          }
          case 26: {
            if (gpsPosition_ == null) {
              GpsPosition = new global::Image.Position();
            }
            input.ReadMessage(GpsPosition);
            break;
          }
          case 34: {
            if (cameraInfo_ == null) {
              CameraInfo = new global::Image.CameraInfo();
            }
            input.ReadMessage(CameraInfo);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Message = input.ReadString();
            break;
          }
          case 18: {
            BytesImage = input.ReadBytes();
            break;
          }
          case 26: {
            if (gpsPosition_ == null) {
              GpsPosition = new global::Image.Position();
            }
            input.ReadMessage(GpsPosition);
            break;
          }
          case 34: {
            if (cameraInfo_ == null) {
              CameraInfo = new global::Image.CameraInfo();
            }
            input.ReadMessage(CameraInfo);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class ImageResponse : pb::IMessage<ImageResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ImageResponse> _parser = new pb::MessageParser<ImageResponse>(() => new ImageResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ImageResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Image.VpsimageReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ImageResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ImageResponse(ImageResponse other) : this() {
      message_ = other.message_;
      accuracy_ = other.accuracy_;
      worldCoor_ = other.worldCoor_ != null ? other.worldCoor_.Clone() : null;
      colmapCoor_ = other.colmapCoor_ != null ? other.colmapCoor_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ImageResponse Clone() {
      return new ImageResponse(this);
    }

    /// <summary>Field number for the "message" field.</summary>
    public const int MessageFieldNumber = 1;
    private string message_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Message {
      get { return message_; }
      set {
        message_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "accuracy" field.</summary>
    public const int AccuracyFieldNumber = 2;
    private float accuracy_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float Accuracy {
      get { return accuracy_; }
      set {
        accuracy_ = value;
      }
    }

    /// <summary>Field number for the "worldCoor" field.</summary>
    public const int WorldCoorFieldNumber = 3;
    private global::Image.WorldCoordinate worldCoor_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Image.WorldCoordinate WorldCoor {
      get { return worldCoor_; }
      set {
        worldCoor_ = value;
      }
    }

    /// <summary>Field number for the "colmapCoor" field.</summary>
    public const int ColmapCoorFieldNumber = 4;
    private global::Image.ColmapCoordinate colmapCoor_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Image.ColmapCoordinate ColmapCoor {
      get { return colmapCoor_; }
      set {
        colmapCoor_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ImageResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ImageResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Message != other.Message) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Accuracy, other.Accuracy)) return false;
      if (!object.Equals(WorldCoor, other.WorldCoor)) return false;
      if (!object.Equals(ColmapCoor, other.ColmapCoor)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Message.Length != 0) hash ^= Message.GetHashCode();
      if (Accuracy != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Accuracy);
      if (worldCoor_ != null) hash ^= WorldCoor.GetHashCode();
      if (colmapCoor_ != null) hash ^= ColmapCoor.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Message.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Message);
      }
      if (Accuracy != 0F) {
        output.WriteRawTag(21);
        output.WriteFloat(Accuracy);
      }
      if (worldCoor_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(WorldCoor);
      }
      if (colmapCoor_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(ColmapCoor);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Message.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Message);
      }
      if (Accuracy != 0F) {
        output.WriteRawTag(21);
        output.WriteFloat(Accuracy);
      }
      if (worldCoor_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(WorldCoor);
      }
      if (colmapCoor_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(ColmapCoor);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Message.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Message);
      }
      if (Accuracy != 0F) {
        size += 1 + 4;
      }
      if (worldCoor_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(WorldCoor);
      }
      if (colmapCoor_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ColmapCoor);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ImageResponse other) {
      if (other == null) {
        return;
      }
      if (other.Message.Length != 0) {
        Message = other.Message;
      }
      if (other.Accuracy != 0F) {
        Accuracy = other.Accuracy;
      }
      if (other.worldCoor_ != null) {
        if (worldCoor_ == null) {
          WorldCoor = new global::Image.WorldCoordinate();
        }
        WorldCoor.MergeFrom(other.WorldCoor);
      }
      if (other.colmapCoor_ != null) {
        if (colmapCoor_ == null) {
          ColmapCoor = new global::Image.ColmapCoordinate();
        }
        ColmapCoor.MergeFrom(other.ColmapCoor);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Message = input.ReadString();
            break;
          }
          case 21: {
            Accuracy = input.ReadFloat();
            break;
          }
          case 26: {
            if (worldCoor_ == null) {
              WorldCoor = new global::Image.WorldCoordinate();
            }
            input.ReadMessage(WorldCoor);
            break;
          }
          case 34: {
            if (colmapCoor_ == null) {
              ColmapCoor = new global::Image.ColmapCoordinate();
            }
            input.ReadMessage(ColmapCoor);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Message = input.ReadString();
            break;
          }
          case 21: {
            Accuracy = input.ReadFloat();
            break;
          }
          case 26: {
            if (worldCoor_ == null) {
              WorldCoor = new global::Image.WorldCoordinate();
            }
            input.ReadMessage(WorldCoor);
            break;
          }
          case 34: {
            if (colmapCoor_ == null) {
              ColmapCoor = new global::Image.ColmapCoordinate();
            }
            input.ReadMessage(ColmapCoor);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class AvailableAreaRequest : pb::IMessage<AvailableAreaRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<AvailableAreaRequest> _parser = new pb::MessageParser<AvailableAreaRequest>(() => new AvailableAreaRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<AvailableAreaRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Image.VpsimageReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AvailableAreaRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AvailableAreaRequest(AvailableAreaRequest other) : this() {
      gpsPosition_ = other.gpsPosition_ != null ? other.gpsPosition_.Clone() : null;
      maxDistance_ = other.maxDistance_;
      minDistance_ = other.minDistance_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AvailableAreaRequest Clone() {
      return new AvailableAreaRequest(this);
    }

    /// <summary>Field number for the "gpsPosition" field.</summary>
    public const int GpsPositionFieldNumber = 1;
    private global::Image.Position gpsPosition_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Image.Position GpsPosition {
      get { return gpsPosition_; }
      set {
        gpsPosition_ = value;
      }
    }

    /// <summary>Field number for the "maxDistance" field.</summary>
    public const int MaxDistanceFieldNumber = 2;
    private int maxDistance_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int MaxDistance {
      get { return maxDistance_; }
      set {
        maxDistance_ = value;
      }
    }

    /// <summary>Field number for the "minDistance" field.</summary>
    public const int MinDistanceFieldNumber = 3;
    private int minDistance_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int MinDistance {
      get { return minDistance_; }
      set {
        minDistance_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as AvailableAreaRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(AvailableAreaRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(GpsPosition, other.GpsPosition)) return false;
      if (MaxDistance != other.MaxDistance) return false;
      if (MinDistance != other.MinDistance) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (gpsPosition_ != null) hash ^= GpsPosition.GetHashCode();
      if (MaxDistance != 0) hash ^= MaxDistance.GetHashCode();
      if (MinDistance != 0) hash ^= MinDistance.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (gpsPosition_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(GpsPosition);
      }
      if (MaxDistance != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(MaxDistance);
      }
      if (MinDistance != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(MinDistance);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (gpsPosition_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(GpsPosition);
      }
      if (MaxDistance != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(MaxDistance);
      }
      if (MinDistance != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(MinDistance);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (gpsPosition_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(GpsPosition);
      }
      if (MaxDistance != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(MaxDistance);
      }
      if (MinDistance != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(MinDistance);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(AvailableAreaRequest other) {
      if (other == null) {
        return;
      }
      if (other.gpsPosition_ != null) {
        if (gpsPosition_ == null) {
          GpsPosition = new global::Image.Position();
        }
        GpsPosition.MergeFrom(other.GpsPosition);
      }
      if (other.MaxDistance != 0) {
        MaxDistance = other.MaxDistance;
      }
      if (other.MinDistance != 0) {
        MinDistance = other.MinDistance;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (gpsPosition_ == null) {
              GpsPosition = new global::Image.Position();
            }
            input.ReadMessage(GpsPosition);
            break;
          }
          case 16: {
            MaxDistance = input.ReadInt32();
            break;
          }
          case 24: {
            MinDistance = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (gpsPosition_ == null) {
              GpsPosition = new global::Image.Position();
            }
            input.ReadMessage(GpsPosition);
            break;
          }
          case 16: {
            MaxDistance = input.ReadInt32();
            break;
          }
          case 24: {
            MinDistance = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class AvailableAreaResponse : pb::IMessage<AvailableAreaResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<AvailableAreaResponse> _parser = new pb::MessageParser<AvailableAreaResponse>(() => new AvailableAreaResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<AvailableAreaResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Image.VpsimageReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AvailableAreaResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AvailableAreaResponse(AvailableAreaResponse other) : this() {
      message_ = other.message_;
      isAvailable_ = other.isAvailable_;
      gpsPosition_ = other.gpsPosition_ != null ? other.gpsPosition_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AvailableAreaResponse Clone() {
      return new AvailableAreaResponse(this);
    }

    /// <summary>Field number for the "message" field.</summary>
    public const int MessageFieldNumber = 1;
    private string message_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Message {
      get { return message_; }
      set {
        message_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "isAvailable" field.</summary>
    public const int IsAvailableFieldNumber = 2;
    private bool isAvailable_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool IsAvailable {
      get { return isAvailable_; }
      set {
        isAvailable_ = value;
      }
    }

    /// <summary>Field number for the "gpsPosition" field.</summary>
    public const int GpsPositionFieldNumber = 3;
    private global::Image.Position gpsPosition_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Image.Position GpsPosition {
      get { return gpsPosition_; }
      set {
        gpsPosition_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as AvailableAreaResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(AvailableAreaResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Message != other.Message) return false;
      if (IsAvailable != other.IsAvailable) return false;
      if (!object.Equals(GpsPosition, other.GpsPosition)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Message.Length != 0) hash ^= Message.GetHashCode();
      if (IsAvailable != false) hash ^= IsAvailable.GetHashCode();
      if (gpsPosition_ != null) hash ^= GpsPosition.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Message.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Message);
      }
      if (IsAvailable != false) {
        output.WriteRawTag(16);
        output.WriteBool(IsAvailable);
      }
      if (gpsPosition_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(GpsPosition);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Message.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Message);
      }
      if (IsAvailable != false) {
        output.WriteRawTag(16);
        output.WriteBool(IsAvailable);
      }
      if (gpsPosition_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(GpsPosition);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Message.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Message);
      }
      if (IsAvailable != false) {
        size += 1 + 1;
      }
      if (gpsPosition_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(GpsPosition);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(AvailableAreaResponse other) {
      if (other == null) {
        return;
      }
      if (other.Message.Length != 0) {
        Message = other.Message;
      }
      if (other.IsAvailable != false) {
        IsAvailable = other.IsAvailable;
      }
      if (other.gpsPosition_ != null) {
        if (gpsPosition_ == null) {
          GpsPosition = new global::Image.Position();
        }
        GpsPosition.MergeFrom(other.GpsPosition);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Message = input.ReadString();
            break;
          }
          case 16: {
            IsAvailable = input.ReadBool();
            break;
          }
          case 26: {
            if (gpsPosition_ == null) {
              GpsPosition = new global::Image.Position();
            }
            input.ReadMessage(GpsPosition);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Message = input.ReadString();
            break;
          }
          case 16: {
            IsAvailable = input.ReadBool();
            break;
          }
          case 26: {
            if (gpsPosition_ == null) {
              GpsPosition = new global::Image.Position();
            }
            input.ReadMessage(GpsPosition);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class Position : pb::IMessage<Position>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Position> _parser = new pb::MessageParser<Position>(() => new Position());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Position> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Image.VpsimageReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Position() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Position(Position other) : this() {
      latitude_ = other.latitude_;
      longitude_ = other.longitude_;
      altitude_ = other.altitude_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Position Clone() {
      return new Position(this);
    }

    /// <summary>Field number for the "latitude" field.</summary>
    public const int LatitudeFieldNumber = 1;
    private double latitude_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double Latitude {
      get { return latitude_; }
      set {
        latitude_ = value;
      }
    }

    /// <summary>Field number for the "longitude" field.</summary>
    public const int LongitudeFieldNumber = 2;
    private double longitude_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double Longitude {
      get { return longitude_; }
      set {
        longitude_ = value;
      }
    }

    /// <summary>Field number for the "altitude" field.</summary>
    public const int AltitudeFieldNumber = 3;
    private double altitude_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double Altitude {
      get { return altitude_; }
      set {
        altitude_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Position);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Position other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Latitude, other.Latitude)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Longitude, other.Longitude)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Altitude, other.Altitude)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Latitude != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Latitude);
      if (Longitude != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Longitude);
      if (Altitude != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Altitude);
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Latitude != 0D) {
        output.WriteRawTag(9);
        output.WriteDouble(Latitude);
      }
      if (Longitude != 0D) {
        output.WriteRawTag(17);
        output.WriteDouble(Longitude);
      }
      if (Altitude != 0D) {
        output.WriteRawTag(25);
        output.WriteDouble(Altitude);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Latitude != 0D) {
        output.WriteRawTag(9);
        output.WriteDouble(Latitude);
      }
      if (Longitude != 0D) {
        output.WriteRawTag(17);
        output.WriteDouble(Longitude);
      }
      if (Altitude != 0D) {
        output.WriteRawTag(25);
        output.WriteDouble(Altitude);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Latitude != 0D) {
        size += 1 + 8;
      }
      if (Longitude != 0D) {
        size += 1 + 8;
      }
      if (Altitude != 0D) {
        size += 1 + 8;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Position other) {
      if (other == null) {
        return;
      }
      if (other.Latitude != 0D) {
        Latitude = other.Latitude;
      }
      if (other.Longitude != 0D) {
        Longitude = other.Longitude;
      }
      if (other.Altitude != 0D) {
        Altitude = other.Altitude;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 9: {
            Latitude = input.ReadDouble();
            break;
          }
          case 17: {
            Longitude = input.ReadDouble();
            break;
          }
          case 25: {
            Altitude = input.ReadDouble();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 9: {
            Latitude = input.ReadDouble();
            break;
          }
          case 17: {
            Longitude = input.ReadDouble();
            break;
          }
          case 25: {
            Altitude = input.ReadDouble();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class WorldCoordinate : pb::IMessage<WorldCoordinate>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<WorldCoordinate> _parser = new pb::MessageParser<WorldCoordinate>(() => new WorldCoordinate());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<WorldCoordinate> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Image.VpsimageReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WorldCoordinate() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WorldCoordinate(WorldCoordinate other) : this() {
      latitude_ = other.latitude_;
      longitude_ = other.longitude_;
      altitude_ = other.altitude_;
      utmX_ = other.utmX_;
      utmY_ = other.utmY_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WorldCoordinate Clone() {
      return new WorldCoordinate(this);
    }

    /// <summary>Field number for the "latitude" field.</summary>
    public const int LatitudeFieldNumber = 1;
    private double latitude_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double Latitude {
      get { return latitude_; }
      set {
        latitude_ = value;
      }
    }

    /// <summary>Field number for the "longitude" field.</summary>
    public const int LongitudeFieldNumber = 2;
    private double longitude_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double Longitude {
      get { return longitude_; }
      set {
        longitude_ = value;
      }
    }

    /// <summary>Field number for the "altitude" field.</summary>
    public const int AltitudeFieldNumber = 3;
    private double altitude_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double Altitude {
      get { return altitude_; }
      set {
        altitude_ = value;
      }
    }

    /// <summary>Field number for the "utm_x" field.</summary>
    public const int UtmXFieldNumber = 4;
    private double utmX_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double UtmX {
      get { return utmX_; }
      set {
        utmX_ = value;
      }
    }

    /// <summary>Field number for the "utm_y" field.</summary>
    public const int UtmYFieldNumber = 5;
    private double utmY_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double UtmY {
      get { return utmY_; }
      set {
        utmY_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as WorldCoordinate);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(WorldCoordinate other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Latitude, other.Latitude)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Longitude, other.Longitude)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Altitude, other.Altitude)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(UtmX, other.UtmX)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(UtmY, other.UtmY)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Latitude != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Latitude);
      if (Longitude != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Longitude);
      if (Altitude != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Altitude);
      if (UtmX != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(UtmX);
      if (UtmY != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(UtmY);
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Latitude != 0D) {
        output.WriteRawTag(9);
        output.WriteDouble(Latitude);
      }
      if (Longitude != 0D) {
        output.WriteRawTag(17);
        output.WriteDouble(Longitude);
      }
      if (Altitude != 0D) {
        output.WriteRawTag(25);
        output.WriteDouble(Altitude);
      }
      if (UtmX != 0D) {
        output.WriteRawTag(33);
        output.WriteDouble(UtmX);
      }
      if (UtmY != 0D) {
        output.WriteRawTag(41);
        output.WriteDouble(UtmY);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Latitude != 0D) {
        output.WriteRawTag(9);
        output.WriteDouble(Latitude);
      }
      if (Longitude != 0D) {
        output.WriteRawTag(17);
        output.WriteDouble(Longitude);
      }
      if (Altitude != 0D) {
        output.WriteRawTag(25);
        output.WriteDouble(Altitude);
      }
      if (UtmX != 0D) {
        output.WriteRawTag(33);
        output.WriteDouble(UtmX);
      }
      if (UtmY != 0D) {
        output.WriteRawTag(41);
        output.WriteDouble(UtmY);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Latitude != 0D) {
        size += 1 + 8;
      }
      if (Longitude != 0D) {
        size += 1 + 8;
      }
      if (Altitude != 0D) {
        size += 1 + 8;
      }
      if (UtmX != 0D) {
        size += 1 + 8;
      }
      if (UtmY != 0D) {
        size += 1 + 8;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(WorldCoordinate other) {
      if (other == null) {
        return;
      }
      if (other.Latitude != 0D) {
        Latitude = other.Latitude;
      }
      if (other.Longitude != 0D) {
        Longitude = other.Longitude;
      }
      if (other.Altitude != 0D) {
        Altitude = other.Altitude;
      }
      if (other.UtmX != 0D) {
        UtmX = other.UtmX;
      }
      if (other.UtmY != 0D) {
        UtmY = other.UtmY;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 9: {
            Latitude = input.ReadDouble();
            break;
          }
          case 17: {
            Longitude = input.ReadDouble();
            break;
          }
          case 25: {
            Altitude = input.ReadDouble();
            break;
          }
          case 33: {
            UtmX = input.ReadDouble();
            break;
          }
          case 41: {
            UtmY = input.ReadDouble();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 9: {
            Latitude = input.ReadDouble();
            break;
          }
          case 17: {
            Longitude = input.ReadDouble();
            break;
          }
          case 25: {
            Altitude = input.ReadDouble();
            break;
          }
          case 33: {
            UtmX = input.ReadDouble();
            break;
          }
          case 41: {
            UtmY = input.ReadDouble();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class ColmapCoordinate : pb::IMessage<ColmapCoordinate>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ColmapCoordinate> _parser = new pb::MessageParser<ColmapCoordinate>(() => new ColmapCoordinate());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ColmapCoordinate> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Image.VpsimageReflection.Descriptor.MessageTypes[6]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ColmapCoordinate() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ColmapCoordinate(ColmapCoordinate other) : this() {
      qw_ = other.qw_;
      qx_ = other.qx_;
      qy_ = other.qy_;
      qz_ = other.qz_;
      tx_ = other.tx_;
      ty_ = other.ty_;
      tz_ = other.tz_;
      px_ = other.px_;
      py_ = other.py_;
      pz_ = other.pz_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ColmapCoordinate Clone() {
      return new ColmapCoordinate(this);
    }

    /// <summary>Field number for the "qw" field.</summary>
    public const int QwFieldNumber = 1;
    private double qw_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double Qw {
      get { return qw_; }
      set {
        qw_ = value;
      }
    }

    /// <summary>Field number for the "qx" field.</summary>
    public const int QxFieldNumber = 2;
    private double qx_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double Qx {
      get { return qx_; }
      set {
        qx_ = value;
      }
    }

    /// <summary>Field number for the "qy" field.</summary>
    public const int QyFieldNumber = 3;
    private double qy_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double Qy {
      get { return qy_; }
      set {
        qy_ = value;
      }
    }

    /// <summary>Field number for the "qz" field.</summary>
    public const int QzFieldNumber = 4;
    private double qz_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double Qz {
      get { return qz_; }
      set {
        qz_ = value;
      }
    }

    /// <summary>Field number for the "tx" field.</summary>
    public const int TxFieldNumber = 5;
    private double tx_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double Tx {
      get { return tx_; }
      set {
        tx_ = value;
      }
    }

    /// <summary>Field number for the "ty" field.</summary>
    public const int TyFieldNumber = 6;
    private double ty_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double Ty {
      get { return ty_; }
      set {
        ty_ = value;
      }
    }

    /// <summary>Field number for the "tz" field.</summary>
    public const int TzFieldNumber = 7;
    private double tz_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double Tz {
      get { return tz_; }
      set {
        tz_ = value;
      }
    }

    /// <summary>Field number for the "px" field.</summary>
    public const int PxFieldNumber = 8;
    private double px_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double Px {
      get { return px_; }
      set {
        px_ = value;
      }
    }

    /// <summary>Field number for the "py" field.</summary>
    public const int PyFieldNumber = 9;
    private double py_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double Py {
      get { return py_; }
      set {
        py_ = value;
      }
    }

    /// <summary>Field number for the "pz" field.</summary>
    public const int PzFieldNumber = 10;
    private double pz_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double Pz {
      get { return pz_; }
      set {
        pz_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ColmapCoordinate);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ColmapCoordinate other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Qw, other.Qw)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Qx, other.Qx)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Qy, other.Qy)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Qz, other.Qz)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Tx, other.Tx)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Ty, other.Ty)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Tz, other.Tz)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Px, other.Px)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Py, other.Py)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Pz, other.Pz)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Qw != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Qw);
      if (Qx != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Qx);
      if (Qy != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Qy);
      if (Qz != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Qz);
      if (Tx != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Tx);
      if (Ty != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Ty);
      if (Tz != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Tz);
      if (Px != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Px);
      if (Py != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Py);
      if (Pz != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Pz);
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Qw != 0D) {
        output.WriteRawTag(9);
        output.WriteDouble(Qw);
      }
      if (Qx != 0D) {
        output.WriteRawTag(17);
        output.WriteDouble(Qx);
      }
      if (Qy != 0D) {
        output.WriteRawTag(25);
        output.WriteDouble(Qy);
      }
      if (Qz != 0D) {
        output.WriteRawTag(33);
        output.WriteDouble(Qz);
      }
      if (Tx != 0D) {
        output.WriteRawTag(41);
        output.WriteDouble(Tx);
      }
      if (Ty != 0D) {
        output.WriteRawTag(49);
        output.WriteDouble(Ty);
      }
      if (Tz != 0D) {
        output.WriteRawTag(57);
        output.WriteDouble(Tz);
      }
      if (Px != 0D) {
        output.WriteRawTag(65);
        output.WriteDouble(Px);
      }
      if (Py != 0D) {
        output.WriteRawTag(73);
        output.WriteDouble(Py);
      }
      if (Pz != 0D) {
        output.WriteRawTag(81);
        output.WriteDouble(Pz);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Qw != 0D) {
        output.WriteRawTag(9);
        output.WriteDouble(Qw);
      }
      if (Qx != 0D) {
        output.WriteRawTag(17);
        output.WriteDouble(Qx);
      }
      if (Qy != 0D) {
        output.WriteRawTag(25);
        output.WriteDouble(Qy);
      }
      if (Qz != 0D) {
        output.WriteRawTag(33);
        output.WriteDouble(Qz);
      }
      if (Tx != 0D) {
        output.WriteRawTag(41);
        output.WriteDouble(Tx);
      }
      if (Ty != 0D) {
        output.WriteRawTag(49);
        output.WriteDouble(Ty);
      }
      if (Tz != 0D) {
        output.WriteRawTag(57);
        output.WriteDouble(Tz);
      }
      if (Px != 0D) {
        output.WriteRawTag(65);
        output.WriteDouble(Px);
      }
      if (Py != 0D) {
        output.WriteRawTag(73);
        output.WriteDouble(Py);
      }
      if (Pz != 0D) {
        output.WriteRawTag(81);
        output.WriteDouble(Pz);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Qw != 0D) {
        size += 1 + 8;
      }
      if (Qx != 0D) {
        size += 1 + 8;
      }
      if (Qy != 0D) {
        size += 1 + 8;
      }
      if (Qz != 0D) {
        size += 1 + 8;
      }
      if (Tx != 0D) {
        size += 1 + 8;
      }
      if (Ty != 0D) {
        size += 1 + 8;
      }
      if (Tz != 0D) {
        size += 1 + 8;
      }
      if (Px != 0D) {
        size += 1 + 8;
      }
      if (Py != 0D) {
        size += 1 + 8;
      }
      if (Pz != 0D) {
        size += 1 + 8;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ColmapCoordinate other) {
      if (other == null) {
        return;
      }
      if (other.Qw != 0D) {
        Qw = other.Qw;
      }
      if (other.Qx != 0D) {
        Qx = other.Qx;
      }
      if (other.Qy != 0D) {
        Qy = other.Qy;
      }
      if (other.Qz != 0D) {
        Qz = other.Qz;
      }
      if (other.Tx != 0D) {
        Tx = other.Tx;
      }
      if (other.Ty != 0D) {
        Ty = other.Ty;
      }
      if (other.Tz != 0D) {
        Tz = other.Tz;
      }
      if (other.Px != 0D) {
        Px = other.Px;
      }
      if (other.Py != 0D) {
        Py = other.Py;
      }
      if (other.Pz != 0D) {
        Pz = other.Pz;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 9: {
            Qw = input.ReadDouble();
            break;
          }
          case 17: {
            Qx = input.ReadDouble();
            break;
          }
          case 25: {
            Qy = input.ReadDouble();
            break;
          }
          case 33: {
            Qz = input.ReadDouble();
            break;
          }
          case 41: {
            Tx = input.ReadDouble();
            break;
          }
          case 49: {
            Ty = input.ReadDouble();
            break;
          }
          case 57: {
            Tz = input.ReadDouble();
            break;
          }
          case 65: {
            Px = input.ReadDouble();
            break;
          }
          case 73: {
            Py = input.ReadDouble();
            break;
          }
          case 81: {
            Pz = input.ReadDouble();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 9: {
            Qw = input.ReadDouble();
            break;
          }
          case 17: {
            Qx = input.ReadDouble();
            break;
          }
          case 25: {
            Qy = input.ReadDouble();
            break;
          }
          case 33: {
            Qz = input.ReadDouble();
            break;
          }
          case 41: {
            Tx = input.ReadDouble();
            break;
          }
          case 49: {
            Ty = input.ReadDouble();
            break;
          }
          case 57: {
            Tz = input.ReadDouble();
            break;
          }
          case 65: {
            Px = input.ReadDouble();
            break;
          }
          case 73: {
            Py = input.ReadDouble();
            break;
          }
          case 81: {
            Pz = input.ReadDouble();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class CameraInfo : pb::IMessage<CameraInfo>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CameraInfo> _parser = new pb::MessageParser<CameraInfo>(() => new CameraInfo());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<CameraInfo> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Image.VpsimageReflection.Descriptor.MessageTypes[7]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CameraInfo() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CameraInfo(CameraInfo other) : this() {
      pixelFocalLength_ = other.pixelFocalLength_;
      principalPointX_ = other.principalPointX_;
      principalPointY_ = other.principalPointY_;
      radialDistortion_ = other.radialDistortion_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CameraInfo Clone() {
      return new CameraInfo(this);
    }

    /// <summary>Field number for the "pixelFocalLength" field.</summary>
    public const int PixelFocalLengthFieldNumber = 1;
    private float pixelFocalLength_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float PixelFocalLength {
      get { return pixelFocalLength_; }
      set {
        pixelFocalLength_ = value;
      }
    }

    /// <summary>Field number for the "principalPointX" field.</summary>
    public const int PrincipalPointXFieldNumber = 2;
    private float principalPointX_;
    /// <summary>
    /// or optical center
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float PrincipalPointX {
      get { return principalPointX_; }
      set {
        principalPointX_ = value;
      }
    }

    /// <summary>Field number for the "principalPointY" field.</summary>
    public const int PrincipalPointYFieldNumber = 3;
    private float principalPointY_;
    /// <summary>
    /// or optical center
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float PrincipalPointY {
      get { return principalPointY_; }
      set {
        principalPointY_ = value;
      }
    }

    /// <summary>Field number for the "radialDistortion" field.</summary>
    public const int RadialDistortionFieldNumber = 4;
    private float radialDistortion_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float RadialDistortion {
      get { return radialDistortion_; }
      set {
        radialDistortion_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as CameraInfo);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(CameraInfo other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(PixelFocalLength, other.PixelFocalLength)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(PrincipalPointX, other.PrincipalPointX)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(PrincipalPointY, other.PrincipalPointY)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(RadialDistortion, other.RadialDistortion)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (PixelFocalLength != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(PixelFocalLength);
      if (PrincipalPointX != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(PrincipalPointX);
      if (PrincipalPointY != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(PrincipalPointY);
      if (RadialDistortion != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(RadialDistortion);
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (PixelFocalLength != 0F) {
        output.WriteRawTag(13);
        output.WriteFloat(PixelFocalLength);
      }
      if (PrincipalPointX != 0F) {
        output.WriteRawTag(21);
        output.WriteFloat(PrincipalPointX);
      }
      if (PrincipalPointY != 0F) {
        output.WriteRawTag(29);
        output.WriteFloat(PrincipalPointY);
      }
      if (RadialDistortion != 0F) {
        output.WriteRawTag(37);
        output.WriteFloat(RadialDistortion);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (PixelFocalLength != 0F) {
        output.WriteRawTag(13);
        output.WriteFloat(PixelFocalLength);
      }
      if (PrincipalPointX != 0F) {
        output.WriteRawTag(21);
        output.WriteFloat(PrincipalPointX);
      }
      if (PrincipalPointY != 0F) {
        output.WriteRawTag(29);
        output.WriteFloat(PrincipalPointY);
      }
      if (RadialDistortion != 0F) {
        output.WriteRawTag(37);
        output.WriteFloat(RadialDistortion);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (PixelFocalLength != 0F) {
        size += 1 + 4;
      }
      if (PrincipalPointX != 0F) {
        size += 1 + 4;
      }
      if (PrincipalPointY != 0F) {
        size += 1 + 4;
      }
      if (RadialDistortion != 0F) {
        size += 1 + 4;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(CameraInfo other) {
      if (other == null) {
        return;
      }
      if (other.PixelFocalLength != 0F) {
        PixelFocalLength = other.PixelFocalLength;
      }
      if (other.PrincipalPointX != 0F) {
        PrincipalPointX = other.PrincipalPointX;
      }
      if (other.PrincipalPointY != 0F) {
        PrincipalPointY = other.PrincipalPointY;
      }
      if (other.RadialDistortion != 0F) {
        RadialDistortion = other.RadialDistortion;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 13: {
            PixelFocalLength = input.ReadFloat();
            break;
          }
          case 21: {
            PrincipalPointX = input.ReadFloat();
            break;
          }
          case 29: {
            PrincipalPointY = input.ReadFloat();
            break;
          }
          case 37: {
            RadialDistortion = input.ReadFloat();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 13: {
            PixelFocalLength = input.ReadFloat();
            break;
          }
          case 21: {
            PrincipalPointX = input.ReadFloat();
            break;
          }
          case 29: {
            PrincipalPointY = input.ReadFloat();
            break;
          }
          case 37: {
            RadialDistortion = input.ReadFloat();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
